CREATE TABLE `sundial_blog_articles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(32) NOT NULL DEFAULT '' COMMENT '唯一ID',
  `title` varchar(1024) NOT NULL COMMENT '标题',
  `category` tinyint(4) NOT NULL DEFAULT '0' COMMENT '分类: 1-,2-,3-,4-',
  `summary` varchar(1024) NOT NULL DEFAULT '' COMMENT '摘要',
  `banner_img_url` varchar(1024) NOT NULL DEFAULT '' COMMENT 'Banner图',
  `normal_img_url` varchar(1024) NOT NULL DEFAULT '' COMMENT 'Normal图, 导入数据为Banner图的裁剪图',
  `share_img_url` varchar(1024) NOT NULL DEFAULT '' COMMENT '分享缩略图',
  `content` longtext,
  `out_link` varchar(1024) NOT NULL DEFAULT '' COMMENT '当content为空时, 使用外链来代替link_url',
  `author` varchar(1024) NOT NULL DEFAULT '' COMMENT '作者',
  `tag_ids` varchar(255) NOT NULL DEFAULT '' COMMENT '原始标签数据+逗号分隔',
  `is_out_show_download` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否在端外展示下载浮层:0-不展示,1-展示',
  `is_top` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否置顶:0-不,1-是',
  `is_banner` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否banner',
  `is_topic` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否是话题文章0-不,1-是',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否上线:0-草稿(暂存),1-下线，2-上线',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除:0-不,1-是',
  `read_count` int(11) NOT NULL DEFAULT '0' COMMENT '阅读数',
  `read_real_count` int(11) NOT NULL DEFAULT '0' COMMENT '真实阅读数',
  `like_count` int(11) NOT NULL DEFAULT '0' COMMENT '点赞数',
  `shared_count` int(11) NOT NULL DEFAULT '0' COMMENT '分享数',
  `comment_count` int(11) NOT NULL DEFAULT '0' COMMENT '精选的评论数',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  `online_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '上线时间',
  `update_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  `creater` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `click_count` int(11) NOT NULL DEFAULT '0' COMMENT '点击数',
  `first_online_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '首次上线时间',
  PRIMARY KEY (`id`),
  KEY `tags` (`tags`),
  KEY `category` (`category`),
  KEY `create_time` (`create_time`),
  KEY `first_online_time` (`first_online_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1024 DEFAULT CHARSET=utf8 COMMENT='文章' |